version: "3.7"

volumes:
  db_data:
  storage:
  traefik_letsencrypt:

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.dashboard=false"                   # Deshabilita el dashboard si no lo necesitas en producción.
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu-email@dominio.com"  # Cambia por tu email.
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_letsencrypt:/letsencrypt"
    restart: unless-stopped

  app:
    image: snipe/snipe-it:${APP_VERSION:-latest}
    restart: unless-stopped
    volumes:
      - storage:/var/lib/snipeit
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.snipeit.rule=Host(`itam.ambarpartners.com`)"
      - "traefik.http.routers.snipeit.entrypoints=websecure"
      - "traefik.http.routers.snipeit.tls.certresolver=myresolver"
      - "traefik.http.services.snipeit.loadbalancer.server.port=80"

  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5
